voornaam = input('Wat is je naam?  ')
achternaam = input('Wat is je achternaam?  ')
postcode1 = input('Wat is je postcode?  ')
woonplaats11 = input('Wat is je woonplaats?  ')
adres1 = input('Wat is je adres?  ')

print(f'-------------------------------------')
print(f'|  Naam:       {voornaam} {achternaam}')    
print(f'|  Adres:      {adres1}')
print(f'|  Postcode:   {postcode1}')
print(f'|  Woonplaats: {woonplaats11}')
print(f'--------------------------------------')